---
- name: Install Docker
  hosts: jenkins
  become: true

  tasks:
    - name: Install required packages
      package:
        name: 
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Add Docker repository
      yum_repository:
        name: docker-ce
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgkey: https://download.docker.com/linux/centos/gpg
      when: ansible_distribution == 'CentOS'

      tasks:

    - name: Install the latest version of docker
      ansible.builtin.dnf:
        name: docker
        state: latest

    - name: Start service docker, if not started
      ansible.builtin.service:
        name: docker
        state: started

    - name: Enable service docker, if not enabled
      ansible.builtin.service:
        name: docker
        enabled: yes


    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      when: ansible_distribution == 'CentOS'
